# Generated by Django 5.1.2 on 2025-06-14 04:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('R', 'Reservado'), ('V', 'Vendido'), ('E', 'En validación')], default='D', max_length=1)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_sorteo', models.DateTimeField()),
                ('premio_principal', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rifas/')),
                ('precio_boleto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boletos_total', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comprobantes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('boleto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='eventos.boleto')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metodo_contacto', models.CharField(choices=[('WS', 'WhatsApp'), ('LL', 'Llamada'), ('FB', 'Facebook'), ('EM', 'Email')], default='WS', max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('reputacion', models.IntegerField(default=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AP', 'Aprobación'), ('RE', 'Rechazo'), ('RE', 'Recordatorio'), ('SO', 'Sorteo')], max_length=2)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.boleto')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.participante')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='eventos.participante'),
        ),
        migrations.CreateModel(
            name='QRBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('boleto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='eventos.boleto')),
            ],
        ),
        migrations.AddField(
            model_name='boleto',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='eventos.rifa'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='boleto',
            unique_together={('rifa', 'numero')},
        ),
    ]
