# Generated by Django 5.1.2 on 2025-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
